#!/usr/bin/python
#
# by Erik Osheim
#
# Use this to create HTML presentation files

from os import listdir
from os.path import join, splitext

boiler1 = open("guts/boiler1.html", "r").read()
boiler2 = open("guts/boiler2.html", "r").read()

for name in listdir('slides'):
    base, _ = splitext(name)
    path = join('slides', name)
    target = join('html', base + '.html')

    print '%s -> %s' % (path, target)

    with open(path, 'r') as f:
        md = f.read()
    with open(target, 'w') as g:
        g.write(boiler1 + "\n" + md + "\n" + boiler2)
